version: '3.7'
services:
  web:
    build:
      context: myapp
    container_name: web
    command: revel run -a web
    expose:
      - 9000
    links:
      - db
    volumes:
      - ./myapp/src:/go/src/
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: ${DOMAIN} # 環境変数で指定する
    depends_on:
      - db
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

  db:
    build: mysql
    container_name: db
    env_file: config/mysql/.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/logs/:/var/log/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: shared
